### ISSUE TITLE
Support for Importing Data from CSV

### ISSUE THREAD

**Issue by jasonrogena** [onaio/ansible-superset#11]
Support importing data sources from CSV by:
 - [x] Default the `UPLOAD_FOLDER` configuration to a directory in the superset user's home directory.
 - [x] Allowing the Superset user to write to the directory specified in the `UPLOAD_FOLDER` configuration.
 - [ ] Adding the `ALLOWED_EXTENSIONS` configuration in [config.py](https://github.com/onaio/ansible-superset/blob/master/templates/config.py.j2). Value should include CSV e.g `set(['csv'])`

**Comment by pld** [comment]
I didn't realize superset had an import CSV feature?

**Comment by jasonrogena** [comment]
Me too. It does under the "Sources" dropdown.

**Comment by pld** [comment]
Huh, interesting, can we set the write directory or the write strategy,
like to have to use s3 or something. I wonder how it indexes the uploaded
file, if it needs file access I guess it'll need to be on disk.

We'll also have to be clear if this is a transient or a persistent store,
and if we want it to persist mirror that directory to s3 on change or
something analogous

**Comment by jasonrogena** [comment]
In our context the data is sent to a transient PostgreSQL store. Not sure what the data engineers want to do with it though. I guess that's more of an issue with internal processes. This issue was more created because the upload from CSV feature is broken.

**Comment by pld** [comment]
OK cool, that's fine then, I'd like if we could specify what folder, it
feels weird to have uploaded CSVs in the packages folder.

**Comment by jasonrogena** [comment]
@pld OK, thanks. I totally agree. I've updated the issue description.
