### ISSUE TITLE
Add support for deploying from source

### ISSUE THREAD

**Issue by moshthepitt** [onaio/ansible-superset#53]
We need to add support for deploying Superset using the source code e.g. something like:

- clone the superset git repository
- compile the js and css
- install superset and its dependencies using pip e.g. pip install requirements, pip install using setup.py etc

**Comment by ukanga** [comment]
Already added by #25. And also the local compilation of assets, see https://github.com/onaio/ansible-superset/commits/master/tasks/compile-assets.yml that was introduced in December.

@moshthepitt what was the intention? all this seem to be in place now.

**Comment by moshthepitt** [comment]
@ukanga yes this is all done now
