### ISSUE TITLE
Further branding Changes

### ISSUE THREAD

**Issue by moshthepitt** [onaio/ansible-superset#9]
Make it possible to change:

- the favicon
- optionally remove/replace the Github link

**Comment by claycrosby** [comment]
I think we should start with just removing the GitHub link, but as Discover usage grows it would be good to replace with a link to where end users can submit issues like some kind of e-HelpDesk

**Comment by engwiri** [comment]
I agree with Clay we should remove the github link for now

**Comment by moshthepitt** [comment]
@claycrosby @engwiri 

Can we get the favicon image?  You can upload it here

**Comment by claycrosby** [comment]
![discovericon](https://user-images.githubusercontent.com/33062840/39745103-fc542b98-52ae-11e8-8538-df393153a99f.png)

**Comment by claycrosby** [comment]
https://drive.google.com/open?id=1mBObUoe2ldbrGkQu1raAlPoQ_SSOGTeo

**Comment by moshthepitt** [comment]
Seems not needed any more.
